#undef KAI_ABS
#undef KAI_ABSX
#undef KAI_ABSY
#undef KAI_IMM
#undef KAI_IMM16
#undef KAI_INDY
#undef KAI_ZP
#undef KAI_ZPX
#undef KA_ABS
#undef KA_ABSX
#undef KA_ABSX_
#undef KA_ABSY
#undef KA_ABSY_
#undef KA_IMM
#undef KA_IMM16
#undef KA_INDX
#undef KA_INDY
#undef KA_INDY_
#undef KA_ZP
#undef KA_ZPX
#undef KA_ZPY
#undef KI_ADDCLOCK
#undef KI_READWORD
#undef KI_READWORDBUG
#undef KI_READWORDZP
#undef KMI_ADC
#undef KMI_SBC
#undef KM_ALUADDER
#undef KM_AND
#undef KM_ASL
#undef KM_BIT
#undef KM_BRA
#undef KM_CMP
#undef KM_CPX
#undef KM_CPY
#undef KM_DEC
#undef KM_EOR
#undef KM_INC
#undef KM_LD
#undef KM_LSR
#undef KM_ORA
#undef KM_POP
#undef KM_PUSH
#undef KM_ROL
#undef KM_ROR
#undef K_OPEXEC
#undef K_READ
#undef K_WRITE
#undef Opcode00
#undef Opcode01
#undef Opcode05
#undef Opcode06
#undef Opcode08
#undef Opcode09
#undef Opcode0A
#undef Opcode0D
#undef Opcode0E
#undef Opcode10
#undef Opcode11
#undef Opcode15
#undef Opcode16
#undef Opcode18
#undef Opcode19
#undef Opcode1D
#undef Opcode1E
#undef Opcode20
#undef Opcode21
#undef Opcode24
#undef Opcode25
#undef Opcode26
#undef Opcode28
#undef Opcode29
#undef Opcode2A
#undef Opcode2C
#undef Opcode2D
#undef Opcode2E
#undef Opcode30
#undef Opcode31
#undef Opcode35
#undef Opcode36
#undef Opcode38
#undef Opcode39
#undef Opcode3D
#undef Opcode3E
#undef Opcode40
#undef Opcode41
#undef Opcode45
#undef Opcode46
#undef Opcode48
#undef Opcode49
#undef Opcode4A
#undef Opcode4C
#undef Opcode4D
#undef Opcode4E
#undef Opcode50
#undef Opcode51
#undef Opcode55
#undef Opcode56
#undef Opcode58
#undef Opcode59
#undef Opcode5D
#undef Opcode5E
#undef Opcode60
#undef Opcode61
#undef Opcode65
#undef Opcode66
#undef Opcode68
#undef Opcode69
#undef Opcode6A
#undef Opcode6C
#undef Opcode6D
#undef Opcode6E
#undef Opcode70
#undef Opcode71
#undef Opcode75
#undef Opcode76
#undef Opcode78
#undef Opcode79
#undef Opcode7D
#undef Opcode7E
#undef Opcode81
#undef Opcode84
#undef Opcode85
#undef Opcode86
#undef Opcode88
#undef Opcode8A
#undef Opcode8C
#undef Opcode8D
#undef Opcode8E
#undef Opcode90
#undef Opcode91
#undef Opcode94
#undef Opcode95
#undef Opcode96
#undef Opcode98
#undef Opcode99
#undef Opcode9A
#undef Opcode9D
#undef OpcodeA0
#undef OpcodeA1
#undef OpcodeA2
#undef OpcodeA4
#undef OpcodeA5
#undef OpcodeA6
#undef OpcodeA8
#undef OpcodeA9
#undef OpcodeAA
#undef OpcodeAC
#undef OpcodeAD
#undef OpcodeAE
#undef OpcodeB0
#undef OpcodeB1
#undef OpcodeB4
#undef OpcodeB5
#undef OpcodeB6
#undef OpcodeB8
#undef OpcodeB9
#undef OpcodeBA
#undef OpcodeBC
#undef OpcodeBD
#undef OpcodeBE
#undef OpcodeC0
#undef OpcodeC1
#undef OpcodeC4
#undef OpcodeC5
#undef OpcodeC6
#undef OpcodeC8
#undef OpcodeC9
#undef OpcodeCA
#undef OpcodeCC
#undef OpcodeCD
#undef OpcodeCE
#undef OpcodeD0
#undef OpcodeD1
#undef OpcodeD5
#undef OpcodeD6
#undef OpcodeD8
#undef OpcodeD9
#undef OpcodeDD
#undef OpcodeDE
#undef OpcodeE0
#undef OpcodeE1
#undef OpcodeE4
#undef OpcodeE5
#undef OpcodeE6
#undef OpcodeE8
#undef OpcodeE9
#undef OpcodeEA
#undef OpcodeEC
#undef OpcodeED
#undef OpcodeEE
#undef OpcodeF0
#undef OpcodeF1
#undef OpcodeF5
#undef OpcodeF6
#undef OpcodeF8
#undef OpcodeF9
#undef OpcodeFD
#undef OpcodeFE
#undef BUILD_M6502
#undef BUILD_M65C02
#undef BUILD_HUC6280
#undef BUILD_2A03
#undef C_FLAG
#undef Z_FLAG
#undef I_FLAG
#undef D_FLAG
#undef B_FLAG
#undef R_FLAG
#undef V_FLAG
#undef N_FLAG
#undef T_FLAG
#undef BASE_OF_ZERO
#undef VEC_RESET
#undef VEC_NMI
#undef VEC_INT
#undef VEC_BRK
#undef IRQ_INIT
#undef IRQ_RESET
#undef IRQ_NMI
#undef IRQ_BRK
#undef IRQ_INT
#undef __THIS__
#undef __CONTEXT
#undef __CONTEXT_
#undef __THISP
#undef __THISP_
#undef K_EXE
#undef __THIS_USER_
#undef __THIS_USER_
#undef K_READNP
#undef K_WRITENP
#undef K_READZP
#undef K_WRITEZP
#undef OPxx
#undef OP__
#undef OP_d
#undef OP_d
#undef OPtd
#undef OPt_
#undef OPtd
#undef OPt_
#undef cl_table
#undef KA_ABSX_
#undef KA_ABSY_
#undef KA_INDY_
#undef DEF_ADC
#undef DEF_ADC
#undef DEF_AND
#undef DEF_AND
#undef DEF_ASL
#undef DEF_BBR
#undef DEF_BBS
#undef DEF_BIT
#undef DEF_BRA
#undef DEF_CMP
#undef DEF_CPX
#undef DEF_CPY
#undef DEF_DEC
#undef DEF_EOR
#undef DEF_EOR
#undef DEF_INC
#undef DEF_JMP
#undef DEF_JMPBUG
#undef DEF_JMPBUG
#undef DEF_LDA
#undef DEF_LDX
#undef DEF_LDY
#undef DEF_LSR
#undef DEF_ORA
#undef DEF_ORA
#undef DEF_RMB
#undef DEF_SMB
#undef DEF_ROL
#undef DEF_ROR
#undef DEF_SBC
#undef DEF_STA
#undef DEF_STX
#undef DEF_STY
#undef DEF_STZ
#undef DEF_TRB
#undef DEF_TSB
#undef DEF_TST
#undef K_EXEC
