#include "device/nes.c"
#include "device/s_dmg.c"
#include "device/s_hes.c"
#include "device/s_hesad.c"
#include "device/s_psg.c"
#include "device/s_scc.c"
#include "device/s_sng.c"
#include "device/opl/s_deltat.c"
#include "device/opl/s_opl.c"
#include "device/opl/s_opltbl.c"

